import logging
import os
from contextlib import asynccontextmanager
from logging.handlers import TimedRotatingFileHandler

from agents import (
    set_default_openai_api,
    set_default_openai_client,
    set_default_openai_key,
    set_tracing_disabled,
)
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from openai import AsyncOpenAI

from .agent.mcp import sarjy_mcp_server
from .core.config import settings
from .core.db import Base, engine
from .routers.chat import router as chat_router
from .routers.health import router as health_router
from .routers.sessions import router as sessions_router

LOG_DIR = "logs"
os.makedirs(LOG_DIR, exist_ok=True)

_log_format = logging.Formatter("%(asctime)s %(levelname)s %(name)s: %(message)s")

_console_handler = logging.StreamHandler()
_console_handler.setFormatter(_log_format)

_file_handler = TimedRotatingFileHandler(
    filename=os.path.join(LOG_DIR, "app.log"),
    when="midnight",
    backupCount=7,
    encoding="utf-8",
)
_file_handler.setFormatter(_log_format)

logging.basicConfig(level=settings.log_level, handlers=[_console_handler, _file_handler])
logger = logging.getLogger(__name__)

API_DESCRIPTION = """
Backend for **Sarjy**, a voice assistant that remembers things across sessions.

Speech-to-text and text-to-speech both run in the browser via the Web Speech
API, so this API only ever handles text.

### Identity

There is no authentication. `user_id` is a UUID generated by the browser and
kept in `localStorage`; the server accepts it as given. Reads are scoped by it
and return `404` for another user's session, which prevents accidental
cross-user reads rather than determined ones. This is a deliberate tradeoff for
a demo, recorded in the project's PRD.

### Sessions

A session row is created lazily, on its first message, so empty conversations
never reach the database. Deleting a session removes its messages but preserves
any memories learned in it — durable facts outlive the conversation that taught
them.
"""

TAGS = [
    {"name": "health", "description": "Liveness, for the platform's health check."},
    {"name": "chat", "description": "One conversational turn."},
    {"name": "sessions", "description": "Conversation history: list, read, rename, delete."},
]


@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("Starting Sarjy API (log_level=%s)", settings.log_level)
    if settings.llm_base_url:
        # Route through the LiteLLM proxy (or any OpenAI-compatible endpoint,
        # e.g. Groq/Gemini) instead of OpenAI directly.
        client = AsyncOpenAI(base_url=settings.llm_base_url, api_key=settings.llm_api_key)
        set_default_openai_client(client)
        set_default_openai_api("chat_completions")  # proxy may not support the Responses API
        set_tracing_disabled(True)  # tracing otherwise posts to OpenAI with the proxy key
    else:
        set_default_openai_key(settings.openai_api_key)
    Base.metadata.create_all(bind=engine)
    await sarjy_mcp_server.connect()
    yield
    await sarjy_mcp_server.cleanup()


app = FastAPI(
    title="Sarjy API",
    version="0.1.0",
    description=API_DESCRIPTION,
    openapi_tags=TAGS,
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=[settings.cors_origin],
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(health_router)
app.include_router(chat_router)
app.include_router(sessions_router)

# The Vite build is copied here by the Docker build. Mounted last so that every
# /api route above wins, and only when present so local `uvicorn --reload` runs
# without a frontend build.
UI_DIST = os.path.join(os.path.dirname(__file__), "static")
if os.path.isdir(UI_DIST):
    app.mount("/", StaticFiles(directory=UI_DIST, html=True), name="ui")
    logger.info("Serving built UI from %s", UI_DIST)
else:
    logger.info("No built UI at %s — API only", UI_DIST)
